define([], function() {
  return {
    WelcomeTitle: "Specify new customer details",
		FormErrorRequiredFields: "Name, Email, and and Company are required.",
		FormLabelName: "Name",
		FormLabelEmail: "Email",
		FormLabelPhone: "Phone:",
		FormLabelAddress: "Address:",
		FormLabelCompany: "Company",
		FormLabelSocialHandle: "Social Handle",
		FormLabelNotes: "Notes:",
		FormPlaceholderName: "Enter customer name",
		FormPlaceholderEmail: "Enter customer email",
		FormPlaceholderPhone: "Enter phone number",
		FormPlaceholderAddress: "Enter address",
		FormPlaceholderCompany: "Enter company",
		FormPlaceholderSocialHandle: "Enter social handle (e.g. @username)",
		FormPlaceholderNotes: "Additional notes",
		FormRequired: "*",
		FormErrorNameRequired: "Name is required.",
		FormErrorEmailRequired: "Email is required.",
		FormErrorCompanyRequired: "Company is required.",
		FormErrorSocialHandleFormat: "Social handle must start with @.",
		FormButtonAddCustomer: "Add Customer",
		FormAlertCustomerAdded: "Customer added: {0} ({1})",
	};
});