name: Deploy SPFx Solution TEST
on:
  push:
    branches:
      - test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NodeVersion: 22.14.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NodeVersion }}
      - name: Run npm ci
        run: npm ci
      - name: Bundle & Package
        run: |
          npm run build
          npm run package-solution:prod
      - name: Run unit tests
        run: npm run test:unit
      - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v3
        with:
          CERTIFICATE_ENCODED: ${{ secrets.M365_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.M365_CERTIFICATE_PASSWORD }}
          APP_ID: ${{ vars.M365_CLIENT_ID }}
          TENANT: ${{ vars.M365_TENANT }}
      - name: CLI for Microsoft 365 Deploy App
        uses: pnp/action-cli-deploy@v5
        with:
          APP_FILE_PATH: sharepoint/solution/espc-spfx-session-demo.sppkg
          SCOPE: sitecollection
          SITE_COLLECTION_URL: ${{ vars.TEST_SHAREPOINT_SITE_APP_CATALOG_URL }}
          SKIP_FEATURE_DEPLOYMENT: false
          OVERWRITE: true
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run tests and update snapshots
        env:
          TEST_SHAREPOINT_SITE_URL: ${{ vars.TEST_SHAREPOINT_SITE_URL }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          npm run test:e2e -- --update-snapshots --project=Chromium
